### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by CastagnaIT** [Enerccio/NFAuthentication#1]
Hi
well these are the required improvements:

## Code side

- the code have to be py2/py3 compatible (often imports problems)
- add missing "# -*- coding: utf-8 -*-" in the header of file
- add missing the \_\_main\_\_ python entry point (where the code effectively start)
- better show/manage the code with sub-functions
- since your code is a python script you should have to create the "requirements.txt" for the required dependencies, but only if there are more than one dependency
- the chrome Port have not to be randomized, or you use the Chrome default dev port, or you have to pick a free port in the system, like netflix service do (better)
- the exceptions are unmanaged and not considered
- for the strings in the code, please use only single accent: ' in to all code, and not double accents "
- To format a string use the new method .format() instead the old %
- add missing SPDX License Identifier + copyright in the file header (you take an example in NF source code)
- add missing license file you can use GPL-3.0-only or similar license
- are you using tempfile.mkdtemp but without a context manager, at the end of script the folder is cleaned?
- i think it is possible avoid the dependecy `websocket` and use the built in `socket` module of python
- full remove the ArgumentParser no arguments
- the output param have to be removed and hardcode "NFAuthentication.key" filename
- add as global variables (all uppercase chars):
PORT = ''
URL = 'https://www.netflix.com/login'
to allow easy customizing (of course if PORT is '' then choose a free port)

i suggest you to use a editor like PyCharm, allow you to check the source code problems in realtime with more python versions, by opening your file as project

## Method of operation

The key point is to make things as easy as possible for novice users, and avoid annoyances to the maintainer and limit the need for support

since this is a script and do not have a UI,
when you start the script
print a "title" with like: "NFAuthentication key - ver. 1.0"
then you have to print also the "Disclaimer" (copy past same of my repo)
the user have to read the dislaimer and to accept/start the script have to press enter

The code can open Chrome, and automatically open the login page
The code can be in wait and automatically recognize when the user is logged, then automatically complete the operations
you can also automatically close chrome at the end of operations

When the code is in awaiting mode, you can print at screen the shortcut key to how force terminate the script (for novices..)

**POST EDIT:** Your code do not have a cookies login validation, this is most important

--

when we have all done i will add to nf addon:
"app_system": "Linux"
"app_author": "ChooseAName"
to recognize the generated key file

and soon we check the login problem

have fun! :)

**Comment by CastagnaIT** [comment]
@Enerccio you have not given any answer
do you think you will finish the script or have you abandoned?

**Comment by Enerccio** [comment]
honestly some of your requirements are insane...

> the code have to be py2/py3 compatible (often imports problems)
> add missing "# -- coding: utf-8 --" in the header of file

literally nobody cares AND py2 should not be used, period

> add missing the __main__ python entry point (where the code effectively start)

completely useless, the only difference is compilation when someone uses it as module (ie no one cares, again)

> better show/manage the code with sub-functions

why? It's a script

> the exceptions are unmanaged and not considered

it's a script, if it crashes it should print exception and be gone

> for the strings in the code, please use only single accent: ' in to all code, and not double accents "
> To format a string use the new method .format() instead the old %

who cares, ffs?

> i think it is possible avoid the dependecy websocket and use the built in socket module of python

too much work for little gain

> POST EDIT: Your code do not have a cookies login validation, this is most important

why? If you are stupid enough to not log in then it wont work... 


These are valid improvements that I am willing to do:

> * since your code is a python script you should have to create the "requirements.txt" for the required dependencies, but only if there are more than one dependency

> add missing license file you can use GPL-3.0-only or similar license

> add missing SPDX License Identifier + copyright in the file header (you take an example in NF source code)

> * add as global variables (all uppercase chars):
> PORT = ''
> URL = 'https://www.netflix.com/login'
> to allow easy customizing (of course if PORT is '' then choose a free port)

> are you using tempfile.mkdtemp but without a context manager, at the end of script the folder is cleaned?


it's in tmp so eventually yes but I can manually remove it

> full remove the ArgumentParser no arguments

> the output param have to be removed and hardcode "NFAuthentication.key" filename


as for whole event loop for chrome, why? Linux users are not morons and they can follow a readme that tells them to log in and go back to script to continue it instead of some crazy event loop with timeout or something

**Comment by CastagnaIT** [comment]
well if this is your position
the discussion end here,
i do not care about people who do things without criteria
thank you for the idea

**Comment by Enerccio** [comment]
such is life
